# Check `docs/pipeline.md` to get info about this file
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: kayen-repository
    type: git
    source:
      uri: https://github.com/kayentech/kayen-website
      branch: master

  - name: pull-requests
      type: pull-request
      source:
        access_token: ((github_token))
        base: master
        private_key: ((git_private_key))
        repo: git@github.com:kayen/website

  - name: kayen-image
    type: docker-image
    source:
      repository: gcr.io/helios-devel/kayen
      username: _json_key
      password: ((gcr_password))

jobs:
  - name: build-pull-request
    plan:
      - get: pull-requests
        trigger: true
      - task: tag
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
          run:
            path: sh
            args: ['-c', 'echo test > tag/name']
          outputs:
            - name: tag
      - put: kayen-image
        params:
          build: pull-requests
          tag: tag/name

  - name: build-master
    serial: true
    plan:
      - get: kayen-repository
        trigger: true
      - put: kayen-image
        params:
          build: kayen-repository

  - name: test-pull-request
    plan:
      - get: pull-requests
        passed:
          - build-pull-request
        trigger: true
      - task: run-tests
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gcr.io/helios-devel/kayen
              tag: test
              username: _json_key
              password: ((gcr_password))
          run:
            path: bash
            args: ["-c", "pushd /pull-requests && npm test"]
          inputs:
            - name: pull-requests
        on_failure:
          put: pull-requests
          params:
            path: pull-requests
            status: failure
        on_success:
          put: pull-requests
          params:
            path: pull-requests
            status: success
